# Generated by Django 5.2.3 on 2025-08-26 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('Manual', 'Manual'), ('AI', 'AI')], default='Manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=255)),
                ('interview_type', models.CharField(choices=[('AI', 'AI-Based Interview'), ('Manual', 'Manual Interview')], default='Manual', max_length=10)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('assigned_questions', models.ManyToManyField(blank=True, to='accounts.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('evaluation', models.CharField(choices=[('correct', 'Correct'), ('incorrect', 'Incorrect'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.candidate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.question')),
            ],
        ),
    ]
